server:
    port: 9090
spring:
    cloud:
        gateway:
            default-filters:
                - name: GlobalFilter
            routes:
                - id: test
                  uri: http://localhost:9091/
                  predicates:
                      - Path=/test/**
                      #- Before=2021-01-20T17:42:47.789-07:00[America/Denver]
                  filters:
                      - name: PreFilter
#                      - name: PostFilter